"""Add timestamp to ECG model

Revision ID: eb9acba80b3e
Revises: 
Create Date: 2024-12-21 13:05:11.222853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb9acba80b3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ecg_data_ibfk_1', 'ecg_data', type_='foreignkey')
    op.create_foreign_key(None, 'ecg_data', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('patients', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('patients', 'height',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('patients', 'weight',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('ecg_data', sa.Column('timestamp', sa.DateTime, nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'weight',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('patients', 'height',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('patients', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'ecg_data', type_='foreignkey')
    op.create_foreign_key('ecg_data_ibfk_1', 'ecg_data', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
